---
# handlers file for ansible-secure

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
- name: restart ufw
  service:
    name: ufw
    state: restarted
- name: restart ssh
  service:
    name: sshd
    state: restarted
